language: ruby
install:
- gem update --system
- gem install rspec card_deck
rvm:
- 1.8.7
- 1.9.2
- 1.9.3
- 2.0.0
- 2.1.0
- 2.1.1
- 2.1.2
- 2.1.3
- ruby-2.2.0-preview1
- jruby-18mode
- jruby-19mode
- ruby-head
script: rspec
matrix:
 fast_finish: true
 allow_failures:
 - rvm: 1.8.7
 - rvm: jruby-18mode
 - rvm: jruby-19mode
 - rvm: ruby-head
before_deploy: chmod a+x bin/99_game
deploy:
  provider: rubygems
  api_key:
    secure: y2bXWjmx+gW5/e9s/Amo76UnL91dsa32rSpOliX4JGHVdGc9jLhAqMLHOpqzVVMzbGNHfcN8ri7WHVV3J+ChefKKYgPqcRujiY9uaM6vPAk5jqTK9Q8UUl06RfJOWumXJfa4Ne7tOI3eKq/HDgbMDWPLiNi5quKpschYxJRndX4=
  gem: 99_game
  on:
    tags: false
    repo: Zrp200/99_game
    rvm: ruby-head
