language: ruby
sudo: false
cache: bundler
install: bundle
rvm: 2.0.0
script: bundle exec rspec -f doc --color
notifications:
 email:
  recipients:
  - 8185408099@vtext.com
  on_success: change
  on_failure: change
matrix:
 fast_finish: true
 allow_failures:
 - rvm: ruby-head
before_deploy: chmod a+x bin/99_game
deploy:
  provider: rubygems
  api_key:
    secure: y2bXWjmx+gW5/e9s/Amo76UnL91dsa32rSpOliX4JGHVdGc9jLhAqMLHOpqzVVMzbGNHfcN8ri7WHVV3J+ChefKKYgPqcRujiY9uaM6vPAk5jqTK9Q8UUl06RfJOWumXJfa4Ne7tOI3eKq/HDgbMDWPLiNi5quKpschYxJRndX4=
  gem: 99_game
  on:
    tags: true
    repo: Zrp200/99_game
