language: ruby
before_install:
- gem update --system
before_script:
- gem install rspec card_deck
rvm:
- 2.1.2
- 2.1.1
- 2.1.0
- 2.0.0
- 1.9.3
- 1.8.7
- 1.9.2
- jruby-18mode
- jruby-19mode
- ruby-head
script:
- gem build 99_game.gemspec
- rspec
matrix:
 fast_finish: true
 allow_failures:
 - rvm: 1.8.7
 - rvm: 1.9.2
 - rvm: jruby-18mode
 - rvm: jruby-19mode
 - rvm: ruby-head
deploy:
  provider: rubygems
  api_key:
    secure: y2bXWjmx+gW5/e9s/Amo76UnL91dsa32rSpOliX4JGHVdGc9jLhAqMLHOpqzVVMzbGNHfcN8ri7WHVV3J+ChefKKYgPqcRujiY9uaM6vPAk5jqTK9Q8UUl06RfJOWumXJfa4Ne7tOI3eKq/HDgbMDWPLiNi5quKpschYxJRndX4=
  gem: 99_game
  on:
    tags: false
    repo: Zrp200/99_game
    rvm: ruby-head
