language: ruby
env: 47984031fb3728b3f3dd3e3b9bd29fd6cae08b2f0a14bd324d31e93d5cd554c6
sudo: false
cache: bundler
install: 
 - bundle
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
rvm: 2.5
before_script: ./cc-test-reporter before-build
script: bundle exec rspec -f doc --color
before_cache: ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
 email:
  recipients:
  - 8185408099@vtext.com
  on_success: change
  on_failure: change
matrix:
 fast_finish: true
 allow_failures:
 - rvm: ruby-head
before_deploy: chmod a+x bin/99_game
deploy:
  provider: rubygems
  api_key:
    secure: y2bXWjmx+gW5/e9s/Amo76UnL91dsa32rSpOliX4JGHVdGc9jLhAqMLHOpqzVVMzbGNHfcN8ri7WHVV3J+ChefKKYgPqcRujiY9uaM6vPAk5jqTK9Q8UUl06RfJOWumXJfa4Ne7tOI3eKq/HDgbMDWPLiNi5quKpschYxJRndX4=
  gem: 99_game
  on:
    tags: true
    repo: Zrp200/99_game
